// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShindaPratice.Models.Shinda;

namespace ShindaPratice.Migrations
{
    [DbContext(typeof(ShindaContext))]
    [Migration("20220101131518_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShindaPratice.Models.Shinda.tblActiveItem", b =>
                {
                    b.Property<int>("cItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("cActiveDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("cItemName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cItemID");

                    b.ToTable("tblActiveItem");
                });

            modelBuilder.Entity("ShindaPratice.Models.Shinda.tblSignup", b =>
                {
                    b.Property<int>("cID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("cCreateDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("cEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cID");

                    b.ToTable("tblSignup");
                });

            modelBuilder.Entity("ShindaPratice.Models.Shinda.tblSignupItem", b =>
                {
                    b.Property<int>("cSignupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cItemID")
                        .HasColumnType("int");

                    b.HasKey("cSignupID");

                    b.ToTable("tblSignupItem");
                });
#pragma warning restore 612, 618
        }
    }
}
